name: Update readme with blog posts
on:
  schedule:
    # Runs every day at 00:00 UTC everyday
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in pradeepl.com posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: https://pradeepl.com/index.xml
          commit_message: "Updated README with the latest blog posts"
          date_format: "mmm d, yyyy"
          custom_tags: "postImage/featured_image/"
          disable_html_encoding: true
          item_exec: |
            post.description = post.description.replace(/<\/?[^>]+(>|$)/g, "").slice(0,100) 
          template: '<table style="width:100%"><tr><td style="width:150px"><a href="$url"><img width="280px" src="$postImage"></a></td><td><a href="$url">$title</a> | $date <br> $description...</td></tr></table>$newline'